"""initial

Revision ID: 0a541e3e8d9d
Revises: 
Create Date: 2026-01-02 15:27:49.843215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a541e3e8d9d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('directors', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_column('directors', 'updated_at')
    op.drop_column('directors', 'created_at')
    op.alter_column('genres', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_column('genres', 'updated_at')
    op.drop_column('genres', 'created_at')
    op.drop_constraint(op.f('movie_genres_movie_id_fkey'), 'movie_genres', type_='foreignkey')
    op.drop_constraint(op.f('movie_genres_genre_id_fkey'), 'movie_genres', type_='foreignkey')
    op.create_foreign_key(None, 'movie_genres', 'genres', ['genre_id'], ['id'])
    op.create_foreign_key(None, 'movie_genres', 'movies', ['movie_id'], ['id'])
    op.alter_column('movie_ratings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_movie_ratings_movie_id'), table_name='movie_ratings')
    op.drop_constraint(op.f('movie_ratings_movie_id_fkey'), 'movie_ratings', type_='foreignkey')
    op.create_foreign_key(None, 'movie_ratings', 'movies', ['movie_id'], ['id'])
    op.alter_column('movies', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('movies', 'release_year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_movies_title'), table_name='movies')
    op.drop_constraint(op.f('movies_director_id_fkey'), 'movies', type_='foreignkey')
    op.create_foreign_key(None, 'movies', 'directors', ['director_id'], ['id'])
    op.drop_column('movies', 'updated_at')
    op.drop_column('movies', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.create_foreign_key(op.f('movies_director_id_fkey'), 'movies', 'directors', ['director_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_movies_title'), 'movies', ['title'], unique=False)
    op.alter_column('movies', 'release_year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('movies', 'title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_constraint(None, 'movie_ratings', type_='foreignkey')
    op.create_foreign_key(op.f('movie_ratings_movie_id_fkey'), 'movie_ratings', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_movie_ratings_movie_id'), 'movie_ratings', ['movie_id'], unique=False)
    op.alter_column('movie_ratings', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'movie_genres', type_='foreignkey')
    op.drop_constraint(None, 'movie_genres', type_='foreignkey')
    op.create_foreign_key(op.f('movie_genres_genre_id_fkey'), 'movie_genres', 'genres', ['genre_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('movie_genres_movie_id_fkey'), 'movie_genres', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    op.add_column('genres', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('genres', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('genres', 'name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.add_column('directors', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('directors', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('directors', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
