"""add_description_to_movies

Revision ID: 2ac0c55ab98a
Revises: 0b7195743eb2
Create Date: 2026-01-02 13:50:03.917432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ac0c55ab98a'
down_revision: Union[str, None] = '0b7195743eb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'description')
    # ### end Alembic commands ###
